# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  #- 5.4

script: phpunit test